- hosts: kube-Slave
  vars_prompt:
  - name: tokens
    prompt: "Join Credentials of Master"
    private: no

  tasks:
  - name: Install Docker Software
    package:
          name: "docker"
          state: present

  - name: Start Docker Service
    service: 
         name: "docker"
         state: started

  - name: Configuring YUM Repo For K8S Services
    yum_repository:
      name: kubernetes
      description: kubernetes repo
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      gpgcheck: 1
      repo_gpgcheck: 1
      enabled: 1
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    register: a
    changed_when: false

  
  - name: Install Kubeadm software..
    shell:
       cmd: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
    ignore_errors: yes

  - name: Start kubelet Service
    service:
        name: "kubelet"
        state: started

  - name: change the driver name for control process by docker
    copy:
       src: daemon.json
       dest: /etc/docker/

  - name: Docker service restarted
    service:
         name: "docker"
         state: restarted
  
  

  - name: Setting Up IP Tables
    copy:
      dest: /etc/sysctl.d/k8s.conf
      content: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1

    changed_when: false

  - name: Restarting sysctl
    shell: "sudo sysctl --system"
    changed_when: false

  - name: Install the tc cmd
    package:
         name: "iproute-tc"
         state: present

  - name: Join master
    shell: "{{ tokens }}"
